### ISSUE TITLE
I remember Lora already provide decomposition for Conv Layer

### ISSUE THREAD

**Issue by Zhidong-Gao** [KohakuBlueleaf/LoCon#10]
I remember Lora already provided the decomposition for the convolution layer:
See this:

https://github.com/cloneofsimo/lora/blob/master/lora_diffusion/lora.py

In **lines 105-123**, their decomposition approach is totally the same as yours.

Any difference between your implementation and Lora's?

**Comment by KohakuBlueleaf** [comment]
For this impl I think it's no different.
I just didn't find this
Sorry

**Comment by KohakuBlueleaf** [comment]
And I'm also planning to do some more different impl on LoRA for conv

**Comment by KohakuBlueleaf** [comment]
@Zhidong-Gao it will be good!!

**Comment by Zhidong-Gao** [comment]
join this discord, and let's discuss the details
https://discord.gg/3SUvg2F4

**Comment by Koronos** [comment]
What this does mean?, LoRA and LoCon actually do the same?

**Comment by KohakuBlueleaf** [comment]
@Koronos Looks the title:
LoRA for Convolution

**Comment by KohakuBlueleaf** [comment]
@Koronos I just expand some existing method to some layer that people never trained on it
