### ISSUE TITLE
Some thoughts, sharing my work here

### ISSUE THREAD

**Issue by cloneofsimo** [KohakuBlueleaf/LoCon#12]
Hey there!

I wanted to share some ideas and my previous implemenations here as well. (Its on diffusers implementation side)

You can use extra lora convolution module with --extend-lora argument on my repo. BTW, when I've explored this about 2 months ago results weren't promising, so it isn't on by default. 
Awesome to see others finding out exploring more on this! I would love to get to know your results

https://github.com/cloneofsimo/lora/pull/133

(Would be appreciated if you mention above pr on this repo's readme, so people can know that there are diffusers compatible implementations as well)

**Comment by KohakuBlueleaf** [comment]
I will migrate this project into new project in this weekend or next.
It will be more complete and has some different algo for parameter-efficent finetune.
I will mentioned your repo at that time.

(When this migration happend, this repo will be renamed into new project name and all LoCon thing will be pushed into a branch)
