### ISSUE TITLE
about filesize and kohya extension

### ISSUE THREAD

**Issue by enranime** [KohakuBlueleaf/LoCon#2]
when I use this with kohya's script the file size is multiply by 2 ? is this normal? I just copy locon folder to kohya sd-scripts then from powershell script I add "--network_module locon.locon_kohya " the result is looking good though.
also is this can only use this via AUTOMATIC1111 only? got an error when try to use in kohya LoRA additional networks extension.

**Comment by KohakuBlueleaf** [comment]
It should multiply by 2 since you train lot more layer with locon

And you should try lower Network_dim and conv_dim than you normally used for lora before

I will recommend conv_dim=4 and network_dim=8

**Comment by KohakuBlueleaf** [comment]
And for as additional network extension
I am digging into it now for loading my model.
It is quite hard to impl it so you may meed to wait for it for  long time

**Comment by enranime** [comment]
> I will recommend conv_dim=4 and network_dim=8
I understand network_dim but what is conv_dim? is this exclusive only LoCon ?
so I just need to add 
--network_args "conv_dim=4" "conv_alpha=4" 
in my script right?

**Comment by enranime** [comment]
sorry If I ask dumb question, as you suggest to use convolution_dim about half as network_dim is this recommended value? is there are a reason for this? or I can just use as same as network_dim

**Comment by KohakuBlueleaf** [comment]
1, not recommend but some of people just use this
2, you can just use same value

**Comment by enranime** [comment]
thanks for answer
