### ISSUE TITLE
error for train

### ISSUE THREAD

**Issue by StupidGame** [KohakuBlueleaf/LoCon#3]
When I run train_network.py, I get the following error just before training.
`Traceback (most recent call last):
		  File "sd-scripts/train_network.py", line 507, in <module>
		    train(args)
		  File "sd-scripts/train_network.py", line 129, in train
		    network = network_module.create_network(1.0, args.network_dim, args.network_alpha, vae, text_encoder, unet, **net_kwargs)
		  File "/content/sd-scripts/LoCon/locon/locon_kohya.py", line 21, in create_network
		    network = LoRANetwork(
		  File "/content/sd-scripts/LoCon/locon/locon_kohya.py", line 121, in __init__
		    self.unet_loras = create_modules(LoRANetwork.LORA_PREFIX_UNET, unet, LoRANetwork.UNET_TARGET_REPLACE_MODULE)
		  File "/content/sd-scripts/LoCon/locon/locon_kohya.py", line 108, in create_modules
		    lora = LoConModule(lora_name, child_module, self.multiplier, self.conv_lora_dim, self.conv_alpha)
		  File "/content/sd-scripts/LoCon/locon/locon.py", line 37, in __init__
		    self.scale = alpha / self.lora_dim
		TypeError: unsupported operand type(s) for /: 'str' and 'int'
		Traceback (most recent call last):
		  File "/usr/local/bin/accelerate", line 8, in <module>
		    sys.exit(main())
		  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
		    args.func(args)
		  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1069, in launch_command
		    simple_launcher(args)
		  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 551, in simple_launcher
		    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
		subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sd-scripts/train_network.py', '--pretrained_model_name_or_path=JosephusCheung/ACertainty', '--train_data_dir=train', '--reg_data_dir=reg', '--network_dim=16', '--network_alpha=8', '--resolution=512', '--output_dir=output', '--prior_loss_weight=1.0', '--train_batch_size=2', '--text_encoder_lr=8.333333333333334e-06', '--unet_lr=5e-05', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=750', '--max_train_steps=3000', '--optimizer_type=Lion', '--mixed_precision=fp16', '--xformers', '--cache_latents', '--gradient_checkpointing', '--save_precision=fp16', '--save_every_n_epochs=2', '--save_model_as=safetensors', '--network_module=LoCon.locon.locon_kohya', '--network_args', 'conv_dim=8', 'conv_alpha=4', '--logging_dir=logs', '--clip_skip=2']' returned non-zero exit status 1.`

Configuration of train_network.py.

`!accelerate launch --num_cpu_threads_per_process 2 sd-scripts/train_network.py \
  --pretrained_model_name_or_path=$pretrained_model_name_or_path \
  --train_data_dir=train \
  --reg_data_dir=reg \
  --network_dim=16 \
  --network_alpha=8 \
  --resolution=512 \
  --output_dir='output' \
  --prior_loss_weight=1.0 \
  --train_batch_size=2 \
  --text_encoder_lr=8e-7\
  --unet_lr=5e-5 \
  --lr_scheduler=cosine_with_restarts \
  --lr_warmup_steps=750 \
  --max_train_steps=3000 \
  --optimizer_type=Lion  \
  --mixed_precision='fp16' \
  --xformers \
  --cache_latents \
  --gradient_checkpointing \
  --save_precision='fp16' \
  --save_every_n_epochs=2 \
  --save_model_as=2 \
  --network_module=LoCon.locon.locon_kohya \
   --network_args "conv_dim=8" "conv_alpha=4" \
  --logging_dir=logs \
  --clip_skip=2`

**Comment by enranime** [comment]
change --network_args "conv_dim=8" "conv_alpha=4"
to --network_args "conv_dim=8 conv_alpha=4" and it's work for me

**Comment by DocShotgun** [comment]
A few of us in a discord I'm in were running into a similar problem as well. It seems that train_network.py is passing the network args over as strings.

Can change line 85 in locon_kohya.py to:
self.conv_alpha = float(conv_alpha)

**Comment by KohakuBlueleaf** [comment]
Solved

**Comment by StupidGame** [comment]
thank you
