### ISSUE TITLE
Make LoCon installation modular

### ISSUE THREAD

**Issue by vladmandic** [KohakuBlueleaf/LoCon#6]
currently installation is to *move locon folder into kohya-ss/sd-scripts*

but that makes local changes to checked-out kohya's repo, so it cannot be cleanly updated any longer.
goal is that this work can reside separately from kohya and still be referenced from `train_network.py` script.

**Comment by KohakuBlueleaf** [comment]
I will do this in these days
make this repo installable through some setup.py or other things

**Comment by KohakuBlueleaf** [comment]
@vladmandic done it
